### ISSUE TITLE
pf2bodyfile | Creation time is not available

### ISSUE THREAD

**Issue by M1ra1B0T** [dfir-dd/dfir-toolkit#26]
I do get the following error message when running pf2bodyfile:
`Error: IO operations error: creation time is not available for the filesystem`

My setup:
- kali linux
- I have connected an external drive with NTFS filesystem.
- An E01 image is stored on the external drive
- I have mounted the E01 image, the mountpath is also on the external drive

**Comment by janstarke** [comment]
That problem should be fixed with a recent version for forensic-rs. Can you please give it a try?

**Comment by M1ra1B0T** [comment]
Just an update to better understand the status of the error. The error is still present as https://github.com/dfir-dd/dfir-toolkit/pull/40 did not succeed.

**Comment by janstarke** [comment]
requires rust 1.78 (see rust-lang/rust#121691)
